### ISSUE TITLE
The `serde` crate needs to be included for server functions to work

### ISSUE THREAD

**Issue by paulvt** [Gentle/start-axum-workspace#6]
The `app` crate should also add a depend on `serde` for server functions to work at all.
If not included, when trying to place `#[server]` methods in there, an error is produced:

```
error[E0463]: can't find crate for `serde`
 --> app/src/lib.rs:7:1
  |
7 | #[server]
  | ^^^^^^^^^ can't find crate
  |
  = note: this error originates in the derive macro `::leptos::server_fn::serde::Serialize` (in Nightly builds, run with -Z macro-backtrace for more info)
```

See also [this discussion](https://github.com/leptos-rs/leptos/discussions/1611).

**Comment by gbj** [comment]
Closing because this is no longer true on 0.6.
